services:
  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
     # ro -> read only for safety
      - ./src:/var/www/html
      # Config PHP, read only
      - ./config/php-upload.ini:/usr/local/etc/php/conf.d/zzz-upload.ini:ro
      # mount separate volumes for writing data
      - uploads-data:/var/www/html/uploads
      - logs-data:/var/log/apache2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 5

  db:
    image: postgres:16-alpine
    env_file:
    - .env
    ports:
      - "5432:5432"   # to connct from host
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  uploads-data:
  logs-data:
  pg-data: